version: '2'

volumes:
  dbvolume:
    external: true
    
services:
  wordpress:
    image: drlogout/wordpress-duplicator:v1.0.0
    ports:
      - 8080:80
    volumes:
      - "./wordpress:/var/www/html"
    restart: always

  mysql:
    image: mariadb:10.1.18
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - "dbvolume:/var/lib/mysql"
    restart: always
    
 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8180:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root 
